//
//  ConstantsItems.swift
//  BackPacker
//
//  Created by Alex Gabets on 19.01.2019.
//  Copyright © 2019 Gabets. All rights reserved.
//

import Foundation

struct ConstantsItems {
    
    let itemsForest = ["item_awning".localized, "item_binoculars".localized, "item_book".localized, "item_bowl".localized, "item_bread".localized, "item_compass".localized, "item_cup".localized, "item_dental_floss".localized, "item_dry_fuel".localized, "item_eBook".localized, "item_first_aid_kit".localized, "item_hat".localized, "item_hatchet".localized, "item_gloves".localized, "item_insulating_tape".localized, "item_keys".localized, "item_kindling".localized, "item_knife".localized, "item_lighter".localized, "item_machete".localized, "item_map".localized, "item_map_case".localized, "item_mat".localized, "item_matches".localized, "item_meat".localized, "item_multi_tool".localized, "item_navigator".localized, "item_needle_thread".localized,                  "item_passport".localized, "item_phone".localized, "item_pocket_mirror".localized, "item_poncho".localized, "item_repellent".localized, "item_rope".localized, "item_salt".localized, "item_saw".localized, "item_seat".localized, "item_sleeping_bag".localized, "item_snacks".localized, "item_soap".localized, "item_socks".localized, "item_spare_batteries".localized, "item_spoon".localized, "item_sugar".localized, "item_tea".localized, "item_tent".localized, "item_thermos".localized, "item_toilet_paper".localized, "item_toothbrush".localized, "item_toothpaste".localized, "item_torch".localized, "item_towel".localized, "item_trekking_poles".localized, "item_veggies".localized, "item_wallet".localized, "item_water_bottle".localized, "item_water_filter".localized, "item_water_flask".localized, "item_wet_wipes".localized]
    
    let itemsBeach = ["item_first_aid_kit".localized, "item_passport".localized, "item_visa".localized, "item_insurance".localized, "item_hotel_reservation".localized, "item_tickets".localized, "item_foreign_currency".localized, "item_razor".localized, "item_cotton_pads".localized, "item_cotton_buds".localized, "item_deodorant".localized, "item_toothbrush".localized, "item_toothpaste".localized, "item_shampoo".localized, "item_hairbrush".localized, "item_cosmetic_bag".localized, "item_charger".localized, "item_house_key".localized, "item_headphones".localized, "item_swimsuit".localized, "item_beach_bag".localized, "item_pareo".localized, "item_beach_towel".localized, "item_flip_flops".localized, "item_sunscreen".localized, "item_hat".localized, "item_after_sun_cream".localized, "item_phone".localized, "item_underwear".localized, "item_shoes".localized, "item_dress".localized, "item_pants".localized, "item_shirt".localized, "item_shorts".localized, "item_skirt".localized, "item_pajamas".localized]
    
    let itemsBusiness = ["item_first_aid_kit".localized, "item_passport".localized, "item_visa".localized, "item_insurance".localized, "item_hotel_reservation".localized, "item_tickets".localized, "item_foreign_currency".localized, "item_razor".localized, "item_cotton_pads".localized, "item_cotton_buds".localized, "item_deodorant".localized, "item_toothbrush".localized, "item_toothpaste".localized, "item_shampoo".localized, "item_hairbrush".localized, "item_cosmetic_bag".localized, "item_house_key".localized, "item_business_cards".localized, "item_laptop".localized, "item_tablet".localized, "item_chargers".localized, "item_diary".localized, "item_underwear".localized, "item_shoes".localized, "item_suit".localized, "item_dress".localized, "item_pants".localized, "item_shirt".localized, "item_pajamas".localized]
}
